// <auto-generated />
using System;
using LLMGateway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LLMGateway.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620083333_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LLMGateway.Data.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Models");
                });

            modelBuilder.Entity("LLMGateway.Data.Models.ModelDeployment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRequestCount")
                        .HasColumnType("integer");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentRequests")
                        .HasColumnType("integer");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderModelId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("ModelDeployments");
                });

            modelBuilder.Entity("LLMGateway.Data.Models.ModelRateLimitBucket", b =>
                {
                    b.Property<int>("ModelRateLimitRuleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer");

                    b.HasKey("ModelRateLimitRuleId", "WindowStartedAt");

                    b.ToTable("ModelRateLimitBuckets");
                });

            modelBuilder.Entity("LLMGateway.Data.Models.ModelRateLimitRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxRequests")
                        .HasColumnType("integer");

                    b.Property<int>("ModelDeploymentId")
                        .HasColumnType("integer");

                    b.Property<int>("WindowSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelDeploymentId");

                    b.ToTable("ModelRateLimitRules");
                });

            modelBuilder.Entity("LLMGateway.Data.Models.ModelDeployment", b =>
                {
                    b.HasOne("LLMGateway.Data.Models.Model", "Model")
                        .WithMany("Deployments")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("LLMGateway.Data.Models.ModelRateLimitBucket", b =>
                {
                    b.HasOne("LLMGateway.Data.Models.ModelRateLimitRule", "ModelRateLimitRule")
                        .WithMany()
                        .HasForeignKey("ModelRateLimitRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelRateLimitRule");
                });

            modelBuilder.Entity("LLMGateway.Data.Models.ModelRateLimitRule", b =>
                {
                    b.HasOne("LLMGateway.Data.Models.ModelDeployment", "ModelDeployment")
                        .WithMany("RateLimitRules")
                        .HasForeignKey("ModelDeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelDeployment");
                });

            modelBuilder.Entity("LLMGateway.Data.Models.Model", b =>
                {
                    b.Navigation("Deployments");
                });

            modelBuilder.Entity("LLMGateway.Data.Models.ModelDeployment", b =>
                {
                    b.Navigation("RateLimitRules");
                });
#pragma warning restore 612, 618
        }
    }
}
